import type { ProjectDocument } from "@douga/project-schema";

export const sampleProject: ProjectDocument = {
  schema_version: 1,
  project_id: "phase-0-spike",
  name: "Renderer spike",
  content_locale: "ja",
  video: { width: 1920, height: 1080, fps: 10 },
  caption_style: {
    x: 140,
    y: 760,
    width: 1640,
    height: 240,
    padding: 42,
    font_family: "Yu Gothic, Meiryo, sans-serif",
    font_size: 58,
    font_weight: 700,
    line_height: 1.35,
    max_lines: 2,
    text_color: "#ffffff",
    background_color: "#07111f",
    background_opacity: 0.84,
    border_radius: 26,
    text_align: "left",
  },
  scenes: [
    {
      id: "scene-1",
      name: "Phase 0",
      background: { type: "color", color: "#16324f" },
      layers: [
        {
          id: "accent",
          type: "shape",
          shape: "rectangle",
          fill: "#3ea6ff",
          x: 140,
          y: 130,
          width: 180,
          height: 14,
          rotation: 0,
          opacity: 1,
        },
        {
          id: "heading",
          type: "text",
          text: "DOUGA / RENDERER SPIKE",
          font_size: 64,
          color: "#ffffff",
          x: 140,
          y: 180,
          width: 1400,
          height: 100,
          rotation: 0,
          opacity: 1,
        },
      ],
      dialogues: [
        {
          id: "dialogue-1",
          speaker: null,
          text: "背景を表示したまま、ノベルゲームのようにテロップが自動的に送られます。",
          display_effect: "typewriter",
          duration_mode: "auto",
          duration_ms: null,
          manual_page_breaks: [],
        },
        {
          id: "dialogue-2",
          speaker: null,
          text: "ブラウザのプレビューと動画書き出しは、同じScene Rendererを使用します。",
          display_effect: "fade",
          duration_mode: "auto",
          duration_ms: null,
          manual_page_breaks: [],
        },
      ],
    },
  ],
};
